CWA.Web/Pages/GrandesClientes/Documentos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CWA.AccessControl;
using CWA.AccessControl.Constants;
using CWA.AccessControl.Services;
using CWA.Application.Services.Comun;
using CWA.Application.Services.GrandesClientes;
using CWA.Entities.Comun;
using CWA.Entities.GrandesClientes;
using CWA.Models.Comun;
using CWA.Models.GrandesClientes.Edit;
using CWA.Models.GrandesClientes.View;
using CWA.Shared.Helpers;
using CWA.Shared.Extensions;
using CWA.Web.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.Extensions.Options;
using Microsoft.Net.Http.Headers;
using CWA.Web.Extensions;
using CWA.AccessControl.Authorization.GrandesClientes;

namespace CWA.Web.Pages.GrandesClientes
{
    [Authorize(Policy = PolicyNames.GCDocumentosPolicy)]
    public class DocumentosModel : PageModel
    {
        // Services
        private readonly GCService _gcdata;
        private readonly GCAccessControlService _gccontrol;
        private readonly AppAccessControlService _access;
        private readonly IOptions<ApplicationSettings> _options;

        // Models
        [BindProperty]
        public GCDocumentoEdit EditModel { get; set; }

        public List<GCDocumentosView> ViewModel { get; set; }
        public List<GCDocumentoSeleccion> Selected { get; set; }

        // Lists
        public List<GCDocumentoList> DocumentosDisponibles = new();

        // Routing
        [BindProperty(SupportsGet = true)]
        public int RegistroId { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? DocumentoId { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Handler { get; set; }

        // Presentation
        public bool ShowUpdate = false;
        public bool ShowApprove = false;
        public bool ShowSelect = false;
        public bool ShowTemplate = false;
        public bool UserApprove = false;
        public string Nombre = "";

        public ViewPack<object> RegistroContext;

        // Options
        readonly string DocumentsRoot;
        readonly string DocumentsTemp;
        readonly string TemplatesPath;

        public DocumentosModel(GCService DataService, GCAccessControlService ControlService, AppAccessControlService Access, IOptions<ApplicationSettings> Options)
        {
            _gcdata = DataService;
            _gccontrol = ControlService;
            _access = Access;
            _options = Options;

            DocumentsRoot = _options.Value.GrandesClientes.DocumentsRoot;
            DocumentsTemp = _options.Value.GrandesClientes.DocumentsTemp;
            TemplatesPath = _options.Value.GrandesClientes.TemplatesPath;

            Selected = new();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            RegistroContext = await _gcdata.ViewRegistroContextAsync(RegistroId);
            RegistroContext.Add("current", "documentos");

            Nombre = $"{RegistroContext["nombre"]}";

            ViewModel = await _gcdata.ViewDocumentosAsync(RegistroId);
            ShowUpdate = await _gccontrol.AllowDocumentosPostAsync(RegistroId, GCConstants.UPDATE);
            UserApprove = await _access.HasClaimAsync(ClaimNames.GCApprove);
            ShowApprove = UserApprove && ViewModel.Where(w => !w.FechaAtencion.HasValue).Any();

            if (ShowUpdate) DocumentosDisponibles = await _gcdata.ViewDocumentosDisponiblesAsync(RegistroId);

            if (ShowApprove && ViewModel.Where(w => !w.FechaAtencion.HasValue).Any())
            {
                ShowSelect = true;
                ViewModel.ForEach(f => Selected.Add(new GCDocumentoSeleccion { Id = f.Id }));
            }

            // Show template only when uploaded
            GCDocumentoDownload template = await _gcdata.ViewTemplateAsync(RegistroId, _gcdata.DOC_PROY, TemplatesPath);
            ShowTemplate = !template.FilePath.Empty();

            return Page();
        }

        public async Task<IActionResult> OnGetTemplateAsync()
        {
            // Get the full physical path, or empty string
            GCDocumentoDownload template = await _gcdata.ViewTemplateAsync(RegistroId, _gcdata.DOC_PROY, TemplatesPath);

            if (template.FilePath.Empty()) return new StatusCodeResult(404);

            // Set response headers
            var provider = new FileExtensionContentTypeProvider();
            var contentDispositionHeader = new ContentDispositionHeaderValue("attachment");
            var cacheHeader = new CacheControlHeaderValue();

            contentDispositionHeader.SetHttpFileName(template.FileName);
            cacheHeader.NoCache = true;

            if (provider.TryGetContentType(template.FilePath, out string contentType))
            {
                Response.Headers[HeaderNames.ContentDisposition] = contentDispositionHeader.ToString();
                Response.Headers[HeaderNames.CacheControl] = cacheHeader.ToString();

                return PhysicalFile(template.FilePath, contentType);
            }

            // If we got here, something went wrong
            return new StatusCodeResult(404);
        }

        public async Task<IActionResult> OnGetDownloadAsync()
        {
            // Get the full physical path, or empty string
            GCDocumentoDownload document = await _gcdata.ViewDocumentoAsync(RegistroId, DocumentoId.Value, DocumentsRoot);

            if (document.FilePath.Empty()) return new StatusCodeResult(404);

            // Set response headers
            var provider = new FileExtensionContentTypeProvider();
            var contentDispositionHeader = new ContentDispositionHeaderValue("inline");
            var cacheHeader = new CacheControlHeaderValue();

            contentDispositionHeader.SetHttpFileName(document.FileName);
            cacheHeader.NoCache = true;

            if (provider.TryGetContentType(document.FilePath, out string contentType))
            {
                Response.Headers[HeaderNames.ContentDisposition] = contentDispositionHeader.ToString();
                Response.Headers[HeaderNames.CacheControl] = cacheHeader.ToString();

                return PhysicalFile(document.FilePath, contentType);
            }

            // If we got here, something went wrong
            return new StatusCodeResult(404);
        }

        public async Task<IActionResult> OnPostUpdateAsync()
        {
            PageOperationResult result = new();

            if (!ModelState.IsValid)
            {
                result.Message = _options.Value.Strings.DatosInvalidos;
                result.Success = false;
                result.Content = ModelState.GetErrorMessages();
                return new JsonResult(result);                
            }

            if (await _gcdata.InvalidFileExtensionAsync(EditModel.DocumentUpload, EditModel.DocumentoId.Value))
            {
                result.Message = _options.Value.GrandesClientes.Strings.ArchivoExtension;
                result.Success = false;
                result.Content = new { Key = "EditModel-DocumentUpload", Message = $"{result.Message}." };
                return new JsonResult(result);
            }

            var registro = await _gcdata.ViewRegistroAsync(RegistroId);

            result = await _gcdata.SaveDocumentoAsync(RegistroId, EditModel, DocumentsRoot, DocumentsTemp, registro.Nombre);

            if (result.Success)
            {
                GCDocumentoResult content = result.Content as GCDocumentoResult;
                content.Actualizado = content.SaveTime.ApplyFormat(_options.Value.DateTimeFormat);
                content.Aprobado = (content.AutoAccepted) ? content.SaveTime.ApplyFormat(_options.Value.DateTimeFormat) : content.Aprobado;
                result.Content = content;
            }

            return new JsonResult(result);
        }

        public async Task<IActionResult> OnPostApproveAsync()
        {
            PageOperationResult result = new();
                        
            if (DocumentoId is null)
            {
                result.Message = _options.Value.GrandesClientes.Strings.NoAprobar;
                result.Success = false;
                return new JsonResult(result);
            }

            result = await _gcdata.ApproveAsync<int, GCDocumento>(DocumentoId.Value, RegistroId, "", IsDocumento: true);
            result.TimeString = (result.TimeValue.HasValue) ? result.TimeValue.Value.ApplyFormat(_options.Value.DateTimeFormat) : "";

            return new JsonResult(result);
        }
    }
}

CWA.Web/Pages/GrandesClientes/Generales.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using CWA.AccessControl;
using CWA.AccessControl.Authorization.GrandesClientes;
using CWA.AccessControl.Constants;
using CWA.AccessControl.Services;
using CWA.Application.Services;
using CWA.Application.Services.Comun;
using CWA.Application.Services.GrandesClientes;
using CWA.Entities.GrandesClientes;
using CWA.Models.Comun;
using CWA.Models.GrandesClientes.Edit;
using CWA.Models.GrandesClientes.View;
using CWA.Shared.Extensions;
using CWA.Shared.Helpers;
using CWA.Web.Extensions;
using CWA.Web.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Options;

namespace CWA.Web.Pages.GrandesClientes
{
    [Authorize(Policy = PolicyNames.GCGeneralesPolicy)]
    public class GeneralesModel : PageModel
    {
        // Services
        private readonly GCService _gcdata;
        private readonly GCAccessControlService _gccontrol;
        private readonly CatalogoService _catalogo;
        private readonly IOptions<ApplicationSettings> _options;

        // Models
        [BindProperty]
        public GCGeneralesEdit EditModel { get; set; }

        public GCGeneralesView ViewModel { get; set; }

        // Lists
        public List<SelectListItem> Provincias = new();

        // Routing
        [BindProperty(SupportsGet = true)]
        public int RegistroId { get; set; }

        [BindProperty(SupportsGet = true)]
        public int GeneralesId { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Handler { get; set; }

        // Presentation
        public bool ShowView = false;
        public bool ShowUpdate = false;
        public bool ShowApprove = false;
        public string Nombre = "";
        public DateTime LastSave;

        public ViewPack<object> RegistroContext;

        public GeneralesModel(GCService DataService, GCAccessControlService ControlService, CatalogoService Catalogo, IOptions<ApplicationSettings> Options)
        {
            _gcdata = DataService;
            _gccontrol = ControlService;
            _catalogo = Catalogo;
            _options = Options;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            // Get related info
            RegistroContext = await _gcdata.ViewRegistroContextAsync<int, GCGenerales>(RegistroId, GeneralesId);
            RegistroContext.Add("current", "generales");

            Nombre = $"{RegistroContext["nombre"]}";
            LastSave = (DateTime)RegistroContext["modfecha"];

            // Check if the item is updatable
            ShowUpdate = await _gccontrol.AllowGeneralesPostAsync(RegistroId, GeneralesId, GCConstants.UPDATE);

            if (ShowUpdate)
            {
                EditModel = await _gcdata.GetDatosAsync<int, GCGenerales, GCGeneralesEdit>(GeneralesId);
                Provincias = await _catalogo.GetForSelectByGrupoAsync("PROVINCIA");
            }
            else
            {
                ShowView = true;
                ViewModel = await _gcdata.ViewDatosAsync<int, GCGenerales, GCGeneralesView>(GeneralesId);
            }

            // Check if item can be approved
            ShowApprove = await _gccontrol.AllowGeneralesPostAsync(RegistroId, GeneralesId, GCConstants.APPROVE);

            return Page();
        }

        public async Task<IActionResult> OnPostUpdateAsync()
        {
            PageOperationResult result = new();

            EditModel.WebUrl = !EditModel.WebUrl.Empty() ? $"http://{EditModel.WebUrl}".ToLower() : EditModel.WebUrl;

            ModelState.ClearValidationState(nameof(EditModel));

            if (!TryValidateModel(EditModel, nameof(EditModel)))
            {
                result.Message = _options.Value.Strings.DatosInvalidos;
                result.Success = false;
                result.Content = ModelState.GetErrorMessages();

                return new JsonResult(result);
            }

            result = await _gcdata.SaveDatosAsync<int, GCGeneralesEdit, GCGenerales>(GeneralesId, EditModel, "GCN04", RegistroId);
            result.TimeString = (result.TimeValue.HasValue) ? result.TimeValue.Value.ApplyFormat(_options.Value.DateTimeFormat) : "";

            return new JsonResult(result);
        }

        public async Task<IActionResult> OnPostApproveAsync()
        {
            PageOperationResult result = new();

            // Validate data
            if (await _gcdata.InvalidItemDataAsync<int, GCGenerales, GCGeneralesEdit>(GeneralesId))
            {
                result.Message = _options.Value.GrandesClientes.Strings.NoAprobar;
                result.Success = false;
                return new JsonResult(result);
            }

            result = await _gcdata.ApproveAsync<int, GCGenerales>(GeneralesId, RegistroId, "GCN04");
            result.TimeString = (result.TimeValue.HasValue) ? result.TimeValue.Value.ApplyFormat(_options.Value.DateTimeFormat) : "";

            return new JsonResult(result);
        }
    }
}

CWA.Web/Pages/GrandesClientes/Registro.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using CWA.AccessControl.Authorization.GrandesClientes;
using CWA.AccessControl.Constants;
using CWA.AccessControl.Services;
using CWA.Application.Services.GrandesClientes;
using CWA.Entities.GrandesClientes;
using CWA.Models.GrandesClientes.View;
using CWA.Shared.Extensions;
using CWA.Shared.Helpers;
using CWA.Web.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace CWA.Web.Pages.GrandesClientes
{
    [Authorize(Policy = PolicyNames.GCRegistroPolicy)]
    public class RegistroModel : PageModel
    {
        // Services
        private readonly GCService _gcdata;
        private readonly GCAccessControlService _gccontrol;
        private readonly IOptions<ApplicationSettings> _options;

        // Models
        [Required]
        [DataType(DataType.Date)]
        [BindProperty]        
        [Display(Name = "Fecha de Entrada")]
        public DateTime? FechaEntrada { get; set; }

        public GCRegistroView ViewModel { get; set; }

        // Routing
        [BindProperty(SupportsGet = true)]
        public int RegistroId { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Handler { get; set; }

        // Presentation
        public bool ShowUpdate = false;
        public bool ShowNotify = false;
        public bool ShowAgente = false;
        public string Nombre = "";

        public ViewPack<object> RegistroContext;

        public RegistroModel(GCService DataService, GCAccessControlService ControlService, IOptions<ApplicationSettings> Options)
        {
            _gcdata = DataService;
            _gccontrol = ControlService;
            _options = Options;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            // Get related info
            RegistroContext = await _gcdata.ViewRegistroContextAsync(RegistroId);
            RegistroContext.Add("current", "registro");

            ViewModel = await _gcdata.ViewRegistroAsync(RegistroId);
            ShowAgente = ViewModel.Tipo == "PASIVO";
            
            ShowUpdate = await _gccontrol.AllowRegistroPostAsync(RegistroId, GCConstants.UPDATE);
            ShowNotify = await _gccontrol.AllowRegistroPostAsync(RegistroId, GCConstants.NOTIFY);

            Nombre = ViewModel.Nombre;
            FechaEntrada = ViewModel.FechaEntrada;            

            return Page();
        }

        public async Task<IActionResult> OnPostUpdateAsync()
        {
            PageOperationResult result = new();

            if (!ModelState.IsValid)
            {
                result.Message = _options.Value.GrandesClientes.Strings.FechaRequerido;
                result.Success = false;
                return new JsonResult(result);
            }

            if (await _gcdata.InvalidFechaEntradaAsync(RegistroId, FechaEntrada.Value))
            {
                result.Message = _options.Value.GrandesClientes.Strings.FechaInvalida;
                result.Success = false;
                return new JsonResult(result);
            }

            result = await _gcdata.SaveFechaEntradaAsync(RegistroId, FechaEntrada.Value, "GCN02");

            result.TimeString = (result.TimeValue.HasValue) ? result.TimeValue.Value.ApplyFormat(_options.Value.DateTimeFormat) : "";

            return new JsonResult(result);
        }

        public async Task<IActionResult> OnPostNotifyAsync()
        {
            PageOperationResult result = await _gcdata.NotifyAuthorizationAsync(RegistroId);
            
            return new JsonResult(result);
        }
    }
}

CWA.Web/Pages/Protecciones/Documentos.cshtml
@page "{registroid:int}/{handler?}/{documentoid:int?}"
@model CWA.Web.Pages.Protecciones.DocumentosModel

@inject IOptions<ApplicationSettings> _options
@inject LinkGenerator _links;

@{
    string aprobado = _options.Value.Protecciones.Strings.ItemAprobado.Aprobado;
    string pendiente = _options.Value.Protecciones.Strings.ItemAprobado.Pendiente;

    List<Breadcrumb> BreadcrumbsModel = new();
    BreadcrumbsModel.Add(new Breadcrumb { Order = 0, Text = Model.RazonSocial });
    BreadcrumbsModel.Add(new Breadcrumb { Order = 1, Text = "Proyectos", Link = _links.GetPathByPage("/Protecciones/Index") });
}

@section PageBreadcrumbsSection {
    <partial name="_BreadcrumbsPartial" model="BreadcrumbsModel" />
}

<!-- link template -->
<a id="cwa-link-template" asp-page-handler="Download" class="d-none"></a>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <partial name="_PROTNavigationPartial" model="Model.InformationContext" />

                <div class="card-body">

                    @* Approve Form *@
                    <form id="cwa-approve-form" asp-page-handler="Approve" method="post"
                          data-ajax="true" data-ajax-method="post" data-ajax-complete="cwa.dialog.complete" novalidate>
                        <div class="table-responsive mb-2">
                            <table id="cwa-documento-table" class="table">
                                <thead>
                                    <tr>
                                        <th>@Html.DisplayNameFor(m => Model.ViewModel[0].Descripcion)</th>
                                        <th class="text-center">@Html.DisplayNameFor(m => Model.ViewModel[0].ModFecha)</th>
                                        <th class="text-center">Estatus</th>
                                        <th class="text-center">@Html.DisplayNameFor(m => Model.ViewModel[0].FechaAprobacion)</th>
                                        <th id="cwa-radio-th" class="text-center" cwa-visible="Model.ShowSelect">Seleccionar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.ViewModel)
                                    {
                                        var current = Model.Selected.Where(w => w.Id == item.Id && !item.FechaAprobacion.HasValue).FirstOrDefault();
                                        bool pending = (current is not null);

                                        <tr data-cwa-rid="@item.Id">
                                            <td class="align-middle">
                                                <a asp-page-handler="Download" asp-route-documentoid="@item.Id">@item.Descripcion</a>
                                            </td>
                                            <td class="text-center align-middle">
                                                <span>@item.ModFecha.ToString(_options.Value.DateTimeFormat)</span>
                                            </td>
                                            <td class="text-center align-middle">
                                                <span cwa-visible="@item.FechaAprobacion.HasValue">@Html.Raw(aprobado + " <i class='bi-check-circle-fill text-success'></i>")</span>
                                                <span cwa-visible="@(!item.FechaAprobacion.HasValue)">@Html.Raw(pendiente + " <i class='bi-clock-fill text-warning'></i>")</span>
                                            </td>
                                            <td class="text-center align-middle">
                                                <span cwa-visible="@item.FechaAprobacion.HasValue">@item.FechaAprobacion.Value.ToString(_options.Value.DateTimeFormat)</span>
                                                <span cwa-visible="@(!item.FechaAprobacion.HasValue)">&nbsp;</span>
                                            </td>
                                            <td class="text-center align-middle" cwa-visible="Model.ShowSelect">
                                                <span cwa-visible="@(!pending)">&nbsp;</span>
                                                @if (pending)
                                                {
                                                    <input class="form-check-input" type="radio" asp-for="DocumentoId" value="@item.Id" />
                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </form>

                    @* Update Form *@
                    <form id="cwa-update-form" asp-page-handler="Update" method="post" enctype="multipart/form-data"
                          data-ajax="true" data-ajax-method="post" data-ajax-complete="cwa.dialog.complete" novalidate cwa-visible="Model.ShowUpload">
                        <div class="row mb-3">
                            <div class="col-12 col-lg mb-2">
                                <label asp-for="EditModel.DocumentoId"></label>
                                <select id="cwa-documento-select" asp-for="EditModel.DocumentoId" class="form-select" asp-items="Model.DocumentosDisponibles">
                                    <option value="">Seleccione un valor...</option>
                                </select>
                                <span cwa-for="EditModel.DocumentoId" class="text-danger cwa-small"></span>
                            </div>
                            <div class="col-12 col-lg mb-2">
                                <label asp-for="EditModel.DocumentUpload"></label>
                                <input id="cwa-fileupload" asp-for="EditModel.DocumentUpload" class="form-control" disabled />
                                <span cwa-for="EditModel.DocumentUpload" class="text-danger cwa-small"></span>
                            </div>
                        </div>
                    </form>

                    @** Buttons *@
                    <div class="container-fluid text-center p-3">
                        <button id="cwa-update-button" type="button" class="btn btn-sm btn-primary me-2" style="width: 100px;" cwa-visible="Model.ShowUpdate">
                            <span>Cargar</span>
                        </button>
                        <button id="cwa-approve-button" type="button" class="btn btn-sm btn-success me-2" style="width: 100px;" cwa-visible="Model.ShowApprove">
                            <span>Aprobar</span>
                        </button>
                        <a asp-page="Index" class="btn btn-sm btn-primary" style="width: 100px;">
                            <span>Regresar</span>
                        </a>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

@if (Model.ShowUpdate || Model.ShowApprove)
{
    @section PageScriptSection {
        <script>
            // Page script properties
            cwa.page.documentosDisponibles = @Html.Raw(Json.Serialize(Model.DocumentosDisponibles));
            cwa.page.strings = {
                aprobado: "@Html.Raw(aprobado)",
                pendiente: "@Html.Raw(pendiente)",
                guardar: "@Html.Raw(_options.Value.Strings.GuardarDatos)",
                aprobar: "@Html.Raw(_options.Value.Strings.AprobarDatos)"
            };
            cwa.page.showUpdate = @(Model.ShowUpdate.ToString().ToLower());
            cwa.page.showApprove = @(Model.ShowApprove.ToString().ToLower());
            cwa.page.userApprove = @(Model.UserApprove.ToString().ToLower());

            // Page dialog properties
            cwa.dialog.parameters = {
                confirmButtonText: "Aceptar",
                cancelButtonText: "Cancelar",
                errorText: "@Html.Raw(_options.Value.Strings.ErrorHttp)"
            };
        </script>

        @* Page specific scripts *@
        <script src="~/esx/pages/protecciones/prot.documentos.js" asp-append-version="true"></script>

        @* Dialog scripts *@
        <script src="~/esx/utils/page-dialog.js" asp-append-version="true"></script>
    }
}

CWA.Web/Pages/Protecciones/Plantillas.cshtml
@page "{registroid:int}/{handler?}/{documentoid:int?}"
@model CWA.Web.Pages.Protecciones.PlantillasModel

@inject IOptions<ApplicationSettings> _options
@inject LinkGenerator _links;

@{
    string aprobado = _options.Value.Protecciones.Strings.ItemAprobado.Aprobado;
    string pendiente = _options.Value.Protecciones.Strings.ItemAprobado.Pendiente;

    List<Breadcrumb> BreadcrumbsModel = new();
    BreadcrumbsModel.Add(new Breadcrumb { Order = 0, Text = Model.RazonSocial });
    BreadcrumbsModel.Add(new Breadcrumb { Order = 1, Text = "Proyectos", Link = _links.GetPathByPage("/Protecciones/Index") });
}

@section PageBreadcrumbsSection {
    <partial name="_BreadcrumbsPartial" model="BreadcrumbsModel" />
}

<!-- link template -->
<a id="cwa-link-template" asp-page-handler="Download" class="d-none"></a>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <partial name="_PROTNavigationPartial" model="Model.InformationContext" />

                <div class="card-body">

                    <div class="table-responsive mb-2">
                        <table id="cwa-documento-table" class="table">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(m => Model.ViewModel[0].Descripcion)</th>
                                    <th class="text-center">@Html.DisplayNameFor(m => Model.ViewModel[0].ModFecha)</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.ViewModel)
                                {
                                    <tr data-cwa-rid="@item.Id">
                                        <td class="align-middle">
                                            <a asp-page-handler="Download" asp-route-plantillaid="@item.Id">@item.Descripcion</a>
                                        </td>
                                        <td class="text-center align-middle">
                                            <span>@item.ModFecha.ToString(_options.Value.DateTimeFormat)</span>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>